In [1]:
import numpy as np

In [2]:
list1=[1,2,3]
a=np.array(list1)
a

array([1, 2, 3])

In [4]:
a.shape

(3,)

In [9]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
b.shape

(2, 4)

In [13]:
print(b[0][1])

2


In [14]:
np.zeros((3),dtype='int64')

array([0, 0, 0])

In [15]:
np.ones(4,dtype='int64')

array([1, 1, 1, 1])

In [16]:
np.full(3,5, dtype='int64')

array([5, 5, 5])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.array(range(12)).reshape(6,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [22]:
np.array(range(12)).reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
np.array(range(24)).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [24]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [26]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [27]:
arr=np.array(lst)

In [28]:
a=arr[:][:]

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a=arr[:,:]

In [31]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
a[::-1,::-1]

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [36]:
b = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11]])
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
b[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [35]:
b[:,0]

array([0, 4, 8])

In [37]:
b[1]

array([4, 5, 6, 7])

In [38]:
b[[0,2],:]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [39]:
print(b[b>5])

[ 6  7  8  9 10 11]


In [40]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a = np.array(lst)
s = a[[0, 1], [1,2]]

In [41]:
s

array([2, 6])

In [42]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]]) 
np.split(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [43]:
np.split(a,(1,3))

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [44]:
np.hsplit(a, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [45]:
np.vsplit(a, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
stack0 = np.stack((a,a))
stack0

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [52]:
stack1=np.stack((a,a),axis=1)
stack1

array([[[ 0,  1,  2,  3],
        [ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [12, 13, 14, 15]]])

In [57]:
a = np.array([[0,1,2,3], [4,5,6,7], [8,9,10,11], [12,13,14,15]]) 
a.flatten()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
c = a + b # c = np.add(a, b)

In [59]:
c

array([5, 7, 9])

# pandas

In [60]:
import pandas as pd

In [61]:
s=pd.Series([1,3,5,7,9])

In [62]:
s

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [64]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [65]:
s.index.name="이름"

In [66]:
s

이름
0    1
1    3
2    5
3    7
4    9
dtype: int64

In [70]:
s.name='숫자'

In [72]:
s

이름
0    1
1    3
2    5
3    7
4    9
Name: 숫자, dtype: int64

In [73]:
pd.Series(range(1,5))

0    1
1    2
2    3
3    4
dtype: int64

In [74]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
index=["서울", "부산", "인천", "대구"])

In [75]:
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [76]:
print(s[:])

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [77]:
print(s[1:3])

부산    3448737
인천    2890451
dtype: int64


In [78]:
s1 = pd.Series(range(3), index=["a", "b", "c"]) 
print(s1.a)

0


In [79]:
s = pd.Series([9904312, 3448737, 2890451, 2466052], index=["서울", "부산", "인천", "대구"])
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천":
2632035, "대젂": 1490158}, index=["부산", "서울", "인천", "대젂"])

In [82]:
ds=s-s2

In [81]:
print(s.values - s2.values)

[ 6511121 -6182745   258416   975894]


In [83]:
ds.notnull()

대구    False
대젂    False
부산     True
서울     True
인천     True
dtype: bool

In [84]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [87]:
df = pd.read_csv('./titanic/train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [89]:
df.isna()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [91]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [92]:
df.groupby("Survived").mean()

PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived                                                                 
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [93]:
df.groupby(["Sex", "Survived"]).mean()

PassengerId    Pclass        Age     SibSp     Parch  \
Sex    Survived                                                         
female 0          434.851852  2.851852  25.046875  1.209877  1.037037   
       1          429.699571  1.918455  28.847716  0.515021  0.515021   
male   0          449.121795  2.476496  31.618056  0.440171  0.207265   
       1          475.724771  2.018349  27.276022  0.385321  0.357798   

                      Fare  
Sex    Survived             
female 0         23.024385  
       1         51.938573  
male   0         21.960993  
       1         40.821484

In [94]:
df1 = df.rename({"Name":"이름"}, axis=1)
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                    이름     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [95]:
df1["이름"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: 이름, Length: 891, dtype: object

In [101]:
df.iloc[:,1:4]

Survived  Pclass                                               Name
0           0       3                            Braund, Mr. Owen Harris
1           1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2           1       3                             Heikkinen, Miss. Laina
3           1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4           0       3                           Allen, Mr. William Henry
..        ...     ...                                                ...
886         0       2                              Montvila, Rev. Juozas
887         1       1                       Graham, Miss. Margaret Edith
888         0       3           Johnston, Miss. Catherine Helen "Carrie"
889         1       1                              Behr, Mr. Karl Howell
890         0       3                                Dooley, Mr. Patrick

[891 rows x 3 columns]

In [102]:
df3 = df.Sex.map(lambda x : 0 if x == "female" else 1)
df3

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

In [105]:
data = {"2015": [9904312, 3448737, 2890451, 2466052], "2010": [9631482, 3393191, 2632035, 2431774], "2005": [9762546, 3512547, 2517680, 2456016], "2000": [9853972, 3655437, 2466338, 2473990],
"지역": ["수도권", "경상권", "수도권", "경상권"], "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
column_list = ["지역", "2015", "2010", "2005", "2000",
"2010-2015 증가율"] 
index_list = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index_list, columns= column_list)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [106]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [107]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [108]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [109]:
df.index.name='도시'
df.columns.name='특성'

In [111]:
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [112]:
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [113]:
df["지역"]

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [114]:
df[["2010","2015"]]

특성     2010     2015
도시                  
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [116]:
type(df["2010"])

pandas.core.series.Series

In [117]:
df2=pd.DataFrame(np.arange(12).reshape(3,4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [118]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int64

In [121]:
df["2010"]['서울']

9631482

In [125]:
df[1:3]

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982

In [128]:
 df = pd.DataFrame({"A":[1,4,7], "B":[2,5,8], "C":[3,6,9]})
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [127]:
df.iloc[0]

A    1
B    2
C    3
Name: 0, dtype: int64

In [129]:
df.loc[0]

A    1
B    2
C    3
Name: 0, dtype: int64

In [130]:
df.loc[:,'A']

0    1
1    4
2    7
Name: A, dtype: int64

In [132]:
df2 = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), index= [2, 'A', 4], columns=[48, 49, 50])
df2

48  49  50
2   1   2   3
A   4   5   6
4   7   8   9

In [133]:
df2.loc[2]

48    1
49    2
50    3
Name: 2, dtype: int64

In [135]:
df2.iloc[2]

48    7
49    8
50    9
Name: 4, dtype: int64

In [136]:
df = pd.read_csv('./titanic/train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [137]:
df.iloc[:5,1:4]

Survived  Pclass                                               Name
0         0       3                            Braund, Mr. Owen Harris
1         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2         1       3                             Heikkinen, Miss. Laina
3         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4         0       3                           Allen, Mr. William Henry

In [138]:
df[["Name", "Sex", "Age"]]

Name     Sex   Age
0                              Braund, Mr. Owen Harris    male  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                               Heikkinen, Miss. Laina  female  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                             Allen, Mr. William Henry    male  35.0
..                                                 ...     ...   ...
886                              Montvila, Rev. Juozas    male  27.0
887                       Graham, Miss. Margaret Edith  female  19.0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889                              Behr, Mr. Karl Howell    male  26.0
890                                Dooley, Mr. Patrick    male  32.0

[891 rows x 3 columns]

In [139]:
df[["Survived"]]

Survived
0           0
1           1
2           1
3           1
4           0
..        ...
886         0
887         1
888         0
889         1
890         0

[891 rows x 1 columns]

In [140]:
df[df["Sex"] == "female"]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
880      1            230433  26.0000   NaN        S  
882      0              7552  10.5167   NaN        S  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 12 columns]

In [141]:
df["Family"]=df["SibSp"]+df["Parch"]

In [142]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Family  
0        0         A/5 21171   7.2500   NaN        S       1  
1        0          PC 17599  71.2833   C85        C       1  
2        0  STON/O2. 3101282   7.9250   NaN        S       0  
3        0            113803  53.1000  C123        S       1  
4        0            373450   8.0500   NaN        S       0  
..     ...               ...      ...   ...      ...     ...  
886      0            211536  13.0000   NaN        S       0  
887      0            112053  30.0000   B42        S       0  
888      2        W./C. 6607  23.4500   NaN        S       3  
889      0            111369  30.0000  C148        C       0  
890      0            370376   7.7500   NaN        Q       0  

[891 rows x 13 columns]

In [143]:
df1=df.rename(columns={"Age":"나이"})

In [144]:
df1

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex    나이  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Family  
0        0         A/5 21171   7.2500   NaN        S       1  
1        0          PC 17599  71.2833   C85        C       1  
2        0  STON/O2. 3101282   7.9250   NaN        S       0  
3        0            113803  53.1000  C123        S       1  
4        0            373450   8.0500   NaN        S       0  
..     ...               ...      ...   ...      ...     ...  
886      0            211536  13.0000   NaN        S       0  
887      0            112053  30.0000   B42        S       0  
888      2        W./C. 6607  23.4500   NaN        S       3  
889      0            111369  30.0000  C148        C       0  
890      0            370376   7.7500   NaN        Q       0  

[891 rows x 13 columns]

In [153]:
df = pd.DataFrame({"A":[1,4,7], "B":[2,5,8], "C":[3,6,9]})
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [154]:
df.set_index("A")

B  C
A      
1  2  3
4  5  6
7  8  9

In [156]:
df = pd.DataFrame(data=np.array([[1,2,3], [4,5,6], [7,8,9]] ), columns=[48, 49, 50])
df

48  49  50
0   1   2   3
1   4   5   6
2   7   8   9

In [158]:
a=pd.DataFrame(data=[[1,2,3]],columns=[48,49,50])
a

48  49  50
0   1   2   3

In [162]:
df=df.append(a)

In [163]:
df=df.reset_index(drop=True)

In [164]:
df

48  49  50
0   1   2   3
1   4   5   6
2   7   8   9
3   1   2   3

In [173]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),columns=["A",'B','C'])
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [174]:
df.drop('A', axis=1, inplace=True) # 열 삭제 print(df)
df

B  C
0  2  3
1  5  6
2  8  9

In [175]:
del df["B"]

In [176]:
df

C
0  3
1  6
2  9

In [183]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],
[40, 50, 60], [23, 35, 37]]), index= [2.5, 12.6, 4.8, 4.8, 2.5],
columns=[48, 49, 50])
df

48  49  50
2.5    1   2   3
12.6   4   5   6
4.8    7   8   9
4.8   40  50  60
2.5   23  35  37

In [184]:
df=df.reset_index()

In [186]:
df=df.drop_duplicates(subset='index', keep='last').set_index('index')

In [187]:
df

48  49  50
index            
12.6    4   5   6
4.8    40  50  60
2.5    23  35  37

In [189]:
df1 = pd.DataFrame({
'고객번호': [1001, 1002, 1003, 1004, 1005, 1006, 1007], '이름': ['둘리', '도우너', '또치', '길동', '희동', '마이콜', '영희']},
columns=['고객번호', '이름'])
df1

고객번호   이름
0  1001   둘리
1  1002  도우너
2  1003   또치
3  1004   길동
4  1005   희동
5  1006  마이콜
6  1007   영희

In [191]:
df2 = pd.DataFrame({'고객번호': [1001, 1001, 1005, 1006, 1008, 1001],
'금액': [10000, 20000, 15000, 5000, 100000, 30000]},
columns=['고객번호', '금액'])
df2

고객번호      금액
0  1001   10000
1  1001   20000
2  1005   15000
3  1006    5000
4  1008  100000
5  1001   30000

In [194]:
df3=pd.merge(df1,df2)
df3

고객번호   이름     금액
0  1001   둘리  10000
1  1001   둘리  20000
2  1001   둘리  30000
3  1005   희동  15000
4  1006  마이콜   5000

In [195]:
pd.merge(df1,df2,how='outer')

고객번호   이름        금액
0  1001   둘리   10000.0
1  1001   둘리   20000.0
2  1001   둘리   30000.0
3  1002  도우너       NaN
4  1003   또치       NaN
5  1004   길동       NaN
6  1005   희동   15000.0
7  1006  마이콜    5000.0
8  1007   영희       NaN
9  1008  NaN  100000.0

In [196]:
pd.merge(df1,df2,how='left')

고객번호   이름       금액
0  1001   둘리  10000.0
1  1001   둘리  20000.0
2  1001   둘리  30000.0
3  1002  도우너      NaN
4  1003   또치      NaN
5  1004   길동      NaN
6  1005   희동  15000.0
7  1006  마이콜   5000.0
8  1007   영희      NaN

In [197]:
pd.merge(df1,df2,how='right')

고객번호   이름      금액
0  1001   둘리   10000
1  1001   둘리   20000
2  1005   희동   15000
3  1006  마이콜    5000
4  1008  NaN  100000
5  1001   둘리   30000

In [198]:
df1 = pd.DataFrame({'품종': ['setosa', 'setosa', 'virginica', 'virginica'], '꽃잎길이': [1.4, 1.3, 1.5, 1.3]}, columns=['품종', '꽃잎길이'])
df2 = pd.DataFrame({'품종': ['setosa', 'virginica', 'virginica', 'versicolor'], '꽃잎너비': [0.4, 0.3, 0.5, 0.3]}, columns=['품종', '꽃잎너비'])
df3 = pd.merge(df1, df2)

In [199]:
df1

품종  꽃잎길이
0     setosa   1.4
1     setosa   1.3
2  virginica   1.5
3  virginica   1.3

In [200]:
df2

품종  꽃잎너비
0      setosa   0.4
1   virginica   0.3
2   virginica   0.5
3  versicolor   0.3

In [201]:
df3

품종  꽃잎길이  꽃잎너비
0     setosa   1.4   0.4
1     setosa   1.3   0.4
2  virginica   1.5   0.3
3  virginica   1.5   0.5
4  virginica   1.3   0.3
5  virginica   1.3   0.5

In [203]:
df1 = pd.DataFrame({ '고객명': ['춖향', '춖향', '몽룡'],
'날짜': ['2018-01-01', '2018-01-02', '2018-01-01'],
'데이터': ['20000', '30000', '100000']}) 
df2 = pd.DataFrame({ '고객명': ['춖향', '몽룡'],
'데이터': ['여자', '남자']})

In [204]:
df1

고객명          날짜     데이터
0  춖향  2018-01-01   20000
1  춖향  2018-01-02   30000
2  몽룡  2018-01-01  100000

In [205]:
df2

고객명 데이터
0  춖향  여자
1  몽룡  남자

In [206]:
pd.merge(df1,df2,on="고객명")

고객명          날짜   데이터_x 데이터_y
0  춖향  2018-01-01   20000    여자
1  춖향  2018-01-02   30000    여자
2  몽룡  2018-01-01  100000    남자

In [207]:
df1 = pd.DataFrame({
'도시': ['서울', '서울', '서울', '부산', '부산'],
'연도': [2000, 2005, 2010, 2000, 2005],
'인구': [9853972, 9762546, 9631482, 3655437, 3512547]}) 
df2 = pd.DataFrame(np.arange(12).reshape((6, 2)),
index=[['부산', '부산', '서울', '서울', '서울', '서울'], [2000, 2005, 2000, 2005, 2010, 2015]],
columns=['데이터1', '데이터2'])

In [208]:
df1

도시    연도       인구
0  서울  2000  9853972
1  서울  2005  9762546
2  서울  2010  9631482
3  부산  2000  3655437
4  부산  2005  3512547

In [209]:
df2

데이터1  데이터2
부산 2000     0     1
   2005     2     3
서울 2000     4     5
   2005     6     7
   2010     8     9
   2015    10    11

In [210]:
pd.merge(df1,df2,left_on=["도시","연도"],right_index=True)

도시    연도       인구  데이터1  데이터2
0  서울  2000  9853972     4     5
1  서울  2005  9762546     6     7
2  서울  2010  9631482     8     9
3  부산  2000  3655437     0     1
4  부산  2005  3512547     2     3

In [211]:
df1 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=['a', 'c', 'e'], columns=['서울', '부산'])
df2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]], index=['b', 'c', 'd', 'e'],
columns=['대구', '광주'])

In [212]:
df1

서울   부산
a  1.0  2.0
c  3.0  4.0
e  5.0  6.0

In [213]:
df2

대구    광주
b   7.0   8.0
c   9.0  10.0
d  11.0  12.0
e  13.0  14.0

In [214]:
pd.merge(df1,df2,how='outer',left_index=True,right_index=True)

서울   부산    대구    광주
a  1.0  2.0   NaN   NaN
b  NaN  NaN   7.0   8.0
c  3.0  4.0   9.0  10.0
d  NaN  NaN  11.0  12.0
e  5.0  6.0  13.0  14.0

In [216]:
s1 = pd.Series([0, 1], index=['A', 'B'])
s2 = pd.Series([2, 3, 4], index=['A', 'B', 'C']) 
s3 = pd.concat([s1, s2])

In [221]:
s3

A    0
B    1
A    2
B    3
C    4
dtype: int64

In [222]:
 df1 = pd.DataFrame(np.arange(6).reshape(3, 2),
index=['a', 'b', 'c'], columns=['데이터1', '데이터2'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'], columns=['데이터3', '데이터4'])
df3 = pd.concat([df1, df2], axis=1)
df3

데이터1  데이터2  데이터3  데이터4
a     0     1   5.0   6.0
b     2     3   NaN   NaN
c     4     5   7.0   8.0

In [223]:
df1

데이터1  데이터2
a     0     1
b     2     3
c     4     5

In [224]:
df2

데이터3  데이터4
a     5     6
c     7     8